# Generated by Django 5.1.4 on 2025-01-14 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='verified',
            field=models.BooleanField(default=False),
        ),
    ]
