# Generated by Django 5.1.4 on 2025-03-22 10:25

import django.db.models.deletion
import django.utils.timezone
import media_toolkit.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProcessedFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original_file', models.FileField(upload_to=media_toolkit.models.get_temp_file_path)),
                ('processed_file', models.FileField(blank=True, null=True, upload_to=media_toolkit.models.get_temp_file_path)),
                ('processing_type', models.CharField(choices=[('format_conversion', 'Format Conversion'), ('image_compression', 'Image Compression'), ('pdf_compression', 'PDF Compression'), ('ocr', 'OCR Text Extraction')], max_length=20)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=10)),
                ('result_text', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('expiration_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
