# Generated by Django 5.1.6 on 2025-03-29 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shortlinks', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='shortlink',
            name='qr_code',
            field=models.ImageField(blank=True, null=True, upload_to='qrcodes/'),
        ),
    ]
