# Generated by Django 5.1.6 on 2025-03-29 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shortlinks', '0003_shortlink_has_custom_qr_qrcodecustomization'),
    ]

    operations = [
        migrations.AddField(
            model_name='qrcodecustomization',
            name='convert_logo_bw',
            field=models.BooleanField(default=False, help_text='Convert logo to black and white'),
        ),
        migrations.AddField(
            model_name='qrcodecustomization',
            name='text',
            field=models.CharField(blank=True, help_text='Text to display below the QR code', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='shortlink',
            name='name',
            field=models.CharField(blank=True, help_text='A friendly name to identify this link', max_length=100, null=True),
        ),
    ]
