# Generated by Django 5.1.6 on 2025-07-29 19:05

import cdn_tool.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CDNFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to=cdn_tool.models.upload_to_hashed_path)),
                ('original_name', models.CharField(max_length=255)),
                ('file_type', models.CharField(max_length=100)),
                ('file_size', models.BigIntegerField()),
                ('upload_date', models.DateTimeField(auto_now_add=True)),
                ('hash_id', models.CharField(db_index=True, max_length=32, unique=True)),
                ('tags', models.CharField(blank=True, help_text='Comma-separated tags', max_length=500)),
                ('description', models.TextField(blank=True)),
                ('download_count', models.PositiveIntegerField(default=0)),
                ('last_accessed', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'CDN File',
                'verbose_name_plural': 'CDN Files',
                'ordering': ['-upload_date'],
            },
        ),
    ]
