# Generated by Django 5.1.6 on 2025-07-29 22:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cdn_tool', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CDNFileCollection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('is_public', models.BooleanField(default=False, help_text='Make this collection publicly accessible')),
            ],
            options={
                'ordering': ['-created_date'],
            },
        ),
        migrations.AddField(
            model_name='cdnfile',
            name='alt_text',
            field=models.CharField(blank=True, help_text='Alt text for images', max_length=255),
        ),
        migrations.AddField(
            model_name='cdnfile',
            name='custom_filename',
            field=models.CharField(blank=True, help_text='Custom filename for downloads', max_length=255),
        ),
        migrations.AddField(
            model_name='cdnfile',
            name='expires_at',
            field=models.DateTimeField(blank=True, help_text='Auto-delete after this date', null=True),
        ),
        migrations.AddField(
            model_name='cdnfile',
            name='image_height',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cdnfile',
            name='image_width',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cdnfile',
            name='is_favorite',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='cdnfile',
            name='is_private',
            field=models.BooleanField(default=False, help_text='Require authentication to access'),
        ),
        migrations.CreateModel(
            name='CDNFileAnalytics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accessed_at', models.DateTimeField(auto_now_add=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('referer', models.URLField(blank=True)),
                ('action', models.CharField(choices=[('view', 'View'), ('download', 'Download'), ('thumbnail', 'Thumbnail')], default='view', max_length=20)),
                ('file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='analytics', to='cdn_tool.cdnfile')),
            ],
            options={
                'verbose_name': 'File Analytics',
                'verbose_name_plural': 'File Analytics',
                'ordering': ['-accessed_at'],
            },
        ),
        migrations.AddField(
            model_name='cdnfile',
            name='collection',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='files', to='cdn_tool.cdnfilecollection'),
        ),
    ]
