# Generated by Django 5.1.6 on 2025-07-29 22:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cdn_tool', '0002_cdnfilecollection_cdnfile_alt_text_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cdnfile',
            name='collection',
        ),
        migrations.RemoveField(
            model_name='cdnfile',
            name='alt_text',
        ),
        migrations.RemoveField(
            model_name='cdnfile',
            name='custom_filename',
        ),
        migrations.RemoveField(
            model_name='cdnfile',
            name='expires_at',
        ),
        migrations.RemoveField(
            model_name='cdnfile',
            name='image_height',
        ),
        migrations.RemoveField(
            model_name='cdnfile',
            name='image_width',
        ),
        migrations.RemoveField(
            model_name='cdnfile',
            name='is_favorite',
        ),
        migrations.RemoveField(
            model_name='cdnfile',
            name='is_private',
        ),
        migrations.DeleteModel(
            name='CDNFileAnalytics',
        ),
        migrations.DeleteModel(
            name='CDNFileCollection',
        ),
    ]
