# Generated by Django 5.1.6 on 2025-07-29 22:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cdn_tool', '0003_remove_cdnfile_collection_remove_cdnfile_alt_text_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cdnfile',
            name='description',
        ),
        migrations.AddField(
            model_name='cdnfile',
            name='display_name',
            field=models.CharField(blank=True, help_text='Custom name for display and downloads', max_length=255),
        ),
        migrations.AddField(
            model_name='cdnfile',
            name='expires_at',
            field=models.DateTimeField(blank=True, help_text='File will be auto-deleted after this date', null=True),
        ),
        migrations.AlterField(
            model_name='cdnfile',
            name='tags',
            field=models.CharField(blank=True, help_text='Comma-separated tags for organization', max_length=500),
        ),
    ]
