# Generated by Django 5.1.6 on 2025-07-29 22:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cdn_tool', '0004_remove_cdnfile_description_cdnfile_display_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cdnfile',
            name='display_name',
        ),
        migrations.RemoveField(
            model_name='cdnfile',
            name='expires_at',
        ),
        migrations.AddField(
            model_name='cdnfile',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='cdnfile',
            name='tags',
            field=models.CharField(blank=True, help_text='Comma-separated tags', max_length=500),
        ),
    ]
