# Generated by Django 5.1.6 on 2025-03-29 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webanalyzer', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='websiteanalysis',
            name='accessibility_score',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='websiteanalysis',
            name='domain_info',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='websiteanalysis',
            name='favicon',
            field=models.URLField(blank=True, max_length=2000, null=True),
        ),
        migrations.AddField(
            model_name='websiteanalysis',
            name='headers',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='websiteanalysis',
            name='meta_tags',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='websiteanalysis',
            name='mobile_friendly',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='websiteanalysis',
            name='page_size',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='websiteanalysis',
            name='performance_score',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='websiteanalysis',
            name='resource_count',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='websiteanalysis',
            name='security_headers',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='websiteanalysis',
            name='seo_score',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='websiteanalysis',
            name='social_media',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='websiteanalysis',
            name='ssl_info',
            field=models.TextField(blank=True, null=True),
        ),
    ]
