# Generated by Django 5.1.6 on 2025-03-29 21:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webanalyzer', '0002_websiteanalysis_accessibility_score_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='websiteanalysis',
            name='accessibility_score',
        ),
        migrations.RemoveField(
            model_name='websiteanalysis',
            name='domain_info',
        ),
        migrations.RemoveField(
            model_name='websiteanalysis',
            name='headers',
        ),
        migrations.RemoveField(
            model_name='websiteanalysis',
            name='performance_score',
        ),
        migrations.RemoveField(
            model_name='websiteanalysis',
            name='resource_count',
        ),
        migrations.RemoveField(
            model_name='websiteanalysis',
            name='security_headers',
        ),
        migrations.RemoveField(
            model_name='websiteanalysis',
            name='seo_score',
        ),
        migrations.RemoveField(
            model_name='websiteanalysis',
            name='ssl_info',
        ),
    ]
