# Generated by Django 5.1.6 on 2025-03-30 18:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webanalyzer', '0003_remove_websiteanalysis_accessibility_score_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='websiteanalysis',
            name='favicon',
        ),
        migrations.RemoveField(
            model_name='websiteanalysis',
            name='meta_tags',
        ),
        migrations.RemoveField(
            model_name='websiteanalysis',
            name='mobile_friendly',
        ),
        migrations.RemoveField(
            model_name='websiteanalysis',
            name='page_size',
        ),
        migrations.RemoveField(
            model_name='websiteanalysis',
            name='social_media',
        ),
    ]
