# Generated by Django 5.1.6 on 2025-03-30 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webanalyzer', '0004_remove_websiteanalysis_favicon_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='websiteanalysis',
            name='favicon',
            field=models.URLField(blank=True, max_length=2000, null=True),
        ),
        migrations.AddField(
            model_name='websiteanalysis',
            name='meta_tags',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='websiteanalysis',
            name='mobile_friendly',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='websiteanalysis',
            name='page_size',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='websiteanalysis',
            name='social_media',
            field=models.TextField(blank=True, null=True),
        ),
    ]
