# Generated by Django 5.1.6 on 2025-03-30 19:52

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LoadTest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('target_url', models.URLField(max_length=2000)),
                ('num_users', models.PositiveIntegerField(default=10, help_text='Number of virtual users to simulate')),
                ('spawn_rate', models.PositiveIntegerField(default=1, help_text='Number of users to spawn per second')),
                ('duration', models.PositiveIntegerField(default=60, help_text='Duration of the test in seconds')),
                ('http_method', models.CharField(choices=[('GET', 'GET'), ('POST', 'POST'), ('PUT', 'PUT'), ('DELETE', 'DELETE')], default='GET', max_length=10)),
                ('headers', models.TextField(blank=True, help_text='HTTP headers in JSON format', null=True)),
                ('body', models.TextField(blank=True, help_text='Request body for POST/PUT requests', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('total_requests', models.PositiveIntegerField(default=0)),
                ('successful_requests', models.PositiveIntegerField(default=0)),
                ('failed_requests', models.PositiveIntegerField(default=0)),
                ('avg_response_time', models.FloatField(blank=True, null=True)),
                ('min_response_time', models.FloatField(blank=True, null=True)),
                ('max_response_time', models.FloatField(blank=True, null=True)),
                ('requests_per_second', models.FloatField(blank=True, null=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='load_tests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Load Test',
                'verbose_name_plural': 'Load Tests',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TestResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('response_time', models.FloatField(blank=True, null=True)),
                ('status_code', models.PositiveIntegerField(blank=True, null=True)),
                ('success', models.BooleanField(default=True)),
                ('error', models.TextField(blank=True)),
                ('test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='webtester.loadtest')),
            ],
            options={
                'ordering': ['timestamp'],
            },
        ),
    ]
