# Generated by Django 5.1.6 on 2025-03-30 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webtester', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='testresult',
            name='user_agent',
            field=models.TextField(blank=True, help_text='User agent used for this request', null=True),
        ),
    ]
