# Generated by Django 5.1.6 on 2025-03-30 21:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webtester', '0003_loadtest_users_data_testresult_content_length_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='JourneyStep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('step_type', models.CharField(choices=[('navigate', 'Navigate to URL'), ('click', 'Click Element'), ('input', 'Input Text'), ('wait', 'Wait'), ('submit', 'Submit Form')], max_length=20)),
                ('order', models.PositiveIntegerField(help_text='Order of execution within the journey')),
                ('url', models.URLField(blank=True, help_text='URL to navigate to (for navigate step type)', max_length=2000, null=True)),
                ('selector', models.CharField(blank=True, help_text='CSS selector for the element (for click, input, submit step types)', max_length=255, null=True)),
                ('value', models.TextField(blank=True, help_text='Value to input (for input step type)', null=True)),
                ('min_wait', models.FloatField(default=1.0, help_text='Minimum wait time in seconds before executing this step')),
                ('max_wait', models.FloatField(default=3.0, help_text='Maximum wait time in seconds before executing this step')),
            ],
            options={
                'ordering': ['journey', 'order'],
            },
        ),
        migrations.AddField(
            model_name='testresult',
            name='step_type',
            field=models.CharField(blank=True, help_text='Type of step that was executed', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='testresult',
            name='url',
            field=models.URLField(blank=True, help_text='URL that was accessed', max_length=2000, null=True),
        ),
        migrations.AddField(
            model_name='testresult',
            name='wait_time',
            field=models.FloatField(blank=True, help_text='Time waited before executing this step', null=True),
        ),
        migrations.AlterField(
            model_name='loadtest',
            name='body',
            field=models.TextField(blank=True, help_text='Request body for POST/PUT requests (not used for journey tests)', null=True),
        ),
        migrations.AlterField(
            model_name='loadtest',
            name='http_method',
            field=models.CharField(choices=[('GET', 'GET'), ('POST', 'POST'), ('PUT', 'PUT'), ('DELETE', 'DELETE')], default='GET', help_text='HTTP method for simple tests (not used for journey tests)', max_length=10),
        ),
        migrations.AlterField(
            model_name='loadtest',
            name='target_url',
            field=models.URLField(blank=True, help_text='Target URL for simple tests (not used for journey tests)', max_length=2000, null=True),
        ),
        migrations.AddField(
            model_name='testresult',
            name='journey_step',
            field=models.ForeignKey(blank=True, help_text='Journey step that generated this result', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='results', to='webtester.journeystep'),
        ),
        migrations.CreateModel(
            name='UserJourney',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('base_url', models.URLField(help_text='Base URL for relative paths in journey steps', max_length=2000)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='journeys', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Journey',
                'verbose_name_plural': 'User Journeys',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='journeystep',
            name='journey',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='steps', to='webtester.userjourney'),
        ),
        migrations.AddField(
            model_name='loadtest',
            name='journey',
            field=models.ForeignKey(blank=True, help_text='User journey to execute (overrides target_url)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='load_tests', to='webtester.userjourney'),
        ),
        migrations.AlterUniqueTogether(
            name='journeystep',
            unique_together={('journey', 'order')},
        ),
    ]
