# Generated by Django 5.1.6 on 2025-03-30 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webtester', '0004_journeystep_testresult_step_type_testresult_url_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TestTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('is_journey', models.BooleanField(default=False, help_text='Whether this template is for a journey test')),
                ('http_method', models.CharField(choices=[('GET', 'GET'), ('POST', 'POST'), ('PUT', 'PUT'), ('DELETE', 'DELETE')], default='GET', max_length=10)),
                ('headers', models.TextField(blank=True, help_text='HTTP headers in JSON format', null=True)),
                ('body', models.TextField(blank=True, help_text='Request body for POST/PUT requests', null=True)),
                ('num_users', models.PositiveIntegerField(default=10, help_text='Default number of virtual users to simulate')),
                ('spawn_rate', models.PositiveIntegerField(default=1, help_text='Default number of users to spawn per second')),
                ('duration', models.PositiveIntegerField(default=60, help_text='Default duration of the test in seconds')),
                ('journey_steps', models.TextField(blank=True, help_text='Journey steps in JSON format', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Test Template',
                'verbose_name_plural': 'Test Templates',
                'ordering': ['name'],
            },
        ),
    ]
