# Generated by Django 5.1.6 on 2025-03-31 12:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webtester', '0005_testtemplate'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='loadtest',
            name='is_public_template',
            field=models.BooleanField(default=False, help_text='Make this test available as a public template for other users'),
        ),
        migrations.AddField(
            model_name='loadtest',
            name='template_description',
            field=models.TextField(blank=True, help_text='Description of what this template does', null=True),
        ),
        migrations.AddField(
            model_name='loadtest',
            name='template_name',
            field=models.CharField(blank=True, help_text='Name to display in the public template library', max_length=100, null=True),
        ),
        migrations.CreateModel(
            name='TestAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assigned_at', models.DateTimeField(auto_now_add=True)),
                ('notes', models.TextField(blank=True, help_text='Notes for the assigned user', null=True)),
                ('assigned_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='test_assignments', to=settings.AUTH_USER_MODEL)),
                ('assigned_to', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assigned_tests', to=settings.AUTH_USER_MODEL)),
                ('test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='webtester.loadtest')),
            ],
            options={
                'ordering': ['-assigned_at'],
                'unique_together': {('test', 'assigned_to')},
            },
        ),
    ]
