# Generated by Django 5.1.6 on 2025-03-31 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webtester', '0006_loadtest_is_public_template_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='loadtest',
            name='journey_probability',
            field=models.FloatField(default=0.7, help_text='Probability (0-1) that a virtual user will use a journey instead of just hitting the target URL'),
        ),
        migrations.AddField(
            model_name='loadtest',
            name='journeys',
            field=models.ManyToManyField(blank=True, help_text='User journeys to execute (overrides target_url)', related_name='load_tests_multi', to='webtester.userjourney'),
        ),
    ]
