# Generated by Django 5.1.6 on 2025-03-31 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webtester', '0007_loadtest_journey_probability_loadtest_journeys'),
    ]

    operations = [
        migrations.AlterField(
            model_name='journeystep',
            name='url',
            field=models.CharField(blank=True, help_text='Path relative to base URL (e.g., /login)', max_length=2000, null=True),
        ),
    ]
